name: physicsx-takehome
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - trimesh~=4.6.13
      - numpy~=2.3.1
      - matplotlib~=3.10.3
      - pytest
      - pylint
      - jupyter
      - mkdocs
      - tqdm
      # Optional extras
      # - pytest~=8.4.1
      # - pytest-cov~=6.2.1
      # - jupyter~=1.1.1
      # - tqdm~=4.67.1
